trigger:
  branches:
    include:
      - none  # ブランチ名は適宜変更してください

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
      
    - task: UseDotNet@2
      displayName: 'Install .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dir
        echo Current directory: %CD%
      displayName: 'List directory contents'

    - script: |
        dotnet restore "$(Build.SourcesDirectory)/MyTutorialFunctionApp/MyTutorialFunctionApp.csproj"
      displayName: 'Restore NuGet packages'

    - script: |
        dotnet build "$(Build.SourcesDirectory)/MyTutorialFunctionApp/MyTutorialFunctionApp.csproj" --configuration Release
      displayName: 'Build project'

    - script: |
        dotnet publish "$(Build.SourcesDirectory)/MyTutorialFunctionApp/MyTutorialFunctionApp.csproj" --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish project'

    - task: ArchiveFiles@2
      displayName: 'Create deployment package'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - deployment: DeployAzureFunctions
    displayName: 'Deploy to Azure Functions'
    environment: 'Your-Azure-Environment'  # 任意の環境名。リリース環境を管理する場合は設定してください
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            
          - script: |
              dir /s /b "$(Pipeline.Workspace)"
            displayName: 'List downloaded artifacts'
            
          - task: AzureFunctionApp@1
            displayName: 'Deploy Azure Functions App'
            inputs:
              azureSubscription: 'armsvc-funcapp'  # Azure サブスクリプションへのサービス接続名
              appType: 'functionApp'
              appName: 'mytutorialfuncapp'  # 作成した Function App の名前
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
